add_test( [==[Simple Dijkstra]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[Simple Dijkstra]==]  )
set_tests_properties( [==[Simple Dijkstra]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[Dijkstra Airport Simple]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[Dijkstra Airport Simple]==]  )
set_tests_properties( [==[Dijkstra Airport Simple]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[Dijkstra Airport Complex]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[Dijkstra Airport Complex]==]  )
set_tests_properties( [==[Dijkstra Airport Complex]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[graph constructor]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[graph constructor]==]  )
set_tests_properties( [==[graph constructor]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[adding and accessing nodes]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[adding and accessing nodes]==]  )
set_tests_properties( [==[adding and accessing nodes]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[connecting nodes]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[connecting nodes]==]  )
set_tests_properties( [==[connecting nodes]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[basic readline test]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[basic readline test]==]  )
set_tests_properties( [==[basic readline test]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[readline with quotes]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[readline with quotes]==]  )
set_tests_properties( [==[readline with quotes]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[delim at ends]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[delim at ends]==]  )
set_tests_properties( [==[delim at ends]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[valid id]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[valid id]==]  )
set_tests_properties( [==[valid id]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[valid iata]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[valid iata]==]  )
set_tests_properties( [==[valid iata]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
add_test( [==[valid longitude and latitude]==] /workspaces/WBLR-CS-225-Project/build_tyler/test [==[valid longitude and latitude]==]  )
set_tests_properties( [==[valid longitude and latitude]==] PROPERTIES WORKING_DIRECTORY /workspaces/WBLR-CS-225-Project/build_tyler)
set( test_TESTS [==[Simple Dijkstra]==] [==[Dijkstra Airport Simple]==] [==[Dijkstra Airport Complex]==] [==[graph constructor]==] [==[adding and accessing nodes]==] [==[connecting nodes]==] [==[basic readline test]==] [==[readline with quotes]==] [==[delim at ends]==] [==[valid id]==] [==[valid iata]==] [==[valid longitude and latitude]==])
